package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.*;
import controller.*;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;
public class FrCadastroLeiturista extends javax.swing.JFrame {
    
    //Para testes ativar a chamada da função criaDados()
    
    private ArrayList<Leiturista> lstUsuarios;
    private ArrayList<Leiturista> lstUsrTemp;
    private boolean flagCancelar;
    private boolean flagEdtSalvar;
    private int indice;
    
    public FrCadastroLeiturista() throws ParseException {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);//Maximizar
        this.formatarCampos();
        this.setVisible(true);
        indice = 0;
        this.lstUsuarios = new ArrayList();
        this.lstUsrTemp = new ArrayList();
        this.flagCancelar = false;
        this.flagEdtSalvar = false;
        this.criaDados(); //Dados para testes
        atualizarTabela();
        this.habilitarCampos(false);
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
        this.txtLog.setEditable(false);
        this.atualizarLog("Programa iniciado.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pnlNovo = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        pnlCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        pnlEditar = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        pnlExcluir = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        pnlSalvar = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        pnlResetar = new javax.swing.JPanel();
        btnResetar = new javax.swing.JButton();
        pnlConsultar = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdUsuarios = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        cbxSexo = new javax.swing.JComboBox<>();
        edtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        ftxCPF = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        ftxDataNasc = new javax.swing.JFormattedTextField();
        pswSenha = new javax.swing.JPasswordField();
        ftxTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        edtSalario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFundo.setBackground(new java.awt.Color(0, 0, 48));
        pnlFundo.setForeground(new java.awt.Color(0, 0, 51));

        pnlTitulo.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Leiturista");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVoltar.setBackground(new java.awt.Color(0, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVoltar.setPreferredSize(new java.awt.Dimension(61, 50));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(352, 352, 352)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNovo.setBackground(new java.awt.Color(0, 153, 153));
        pnlNovo.setPreferredSize(new java.awt.Dimension(95, 50));

        btnNovo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.setContentAreaFilled(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNovoLayout = new javax.swing.GroupLayout(pnlNovo);
        pnlNovo.setLayout(pnlNovoLayout);
        pnlNovoLayout.setHorizontalGroup(
            pnlNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNovoLayout.setVerticalGroup(
            pnlNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlCancelar.setBackground(new java.awt.Color(0, 153, 153));
        pnlCancelar.setPreferredSize(new java.awt.Dimension(135, 50));

        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(135, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCancelarLayout = new javax.swing.GroupLayout(pnlCancelar);
        pnlCancelar.setLayout(pnlCancelarLayout);
        pnlCancelarLayout.setHorizontalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCancelarLayout.setVerticalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlEditar.setBackground(new java.awt.Color(0, 153, 153));
        pnlEditar.setPreferredSize(new java.awt.Dimension(101, 50));

        btnEditar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPreferredSize(new java.awt.Dimension(101, 50));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlExcluir.setBackground(new java.awt.Color(0, 153, 153));
        pnlExcluir.setPreferredSize(new java.awt.Dimension(111, 50));

        btnExcluir.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setPreferredSize(new java.awt.Dimension(111, 50));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExcluirLayout = new javax.swing.GroupLayout(pnlExcluir);
        pnlExcluir.setLayout(pnlExcluirLayout);
        pnlExcluirLayout.setHorizontalGroup(
            pnlExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlExcluirLayout.setVerticalGroup(
            pnlExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSalvar.setBackground(new java.awt.Color(0, 153, 153));
        pnlSalvar.setPreferredSize(new java.awt.Dimension(107, 50));

        btnSalvar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setPreferredSize(new java.awt.Dimension(107, 50));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalvarLayout = new javax.swing.GroupLayout(pnlSalvar);
        pnlSalvar.setLayout(pnlSalvarLayout);
        pnlSalvarLayout.setHorizontalGroup(
            pnlSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSalvarLayout.setVerticalGroup(
            pnlSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlResetar.setBackground(new java.awt.Color(0, 153, 153));

        btnResetar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnResetar.setForeground(new java.awt.Color(255, 255, 255));
        btnResetar.setText("Resetar");
        btnResetar.setBorderPainted(false);
        btnResetar.setContentAreaFilled(false);
        btnResetar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnResetar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetar.setPreferredSize(new java.awt.Dimension(123, 50));
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResetarLayout = new javax.swing.GroupLayout(pnlResetar);
        pnlResetar.setLayout(pnlResetarLayout);
        pnlResetarLayout.setHorizontalGroup(
            pnlResetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlResetarLayout.setVerticalGroup(
            pnlResetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlConsultar.setBackground(new java.awt.Color(0, 153, 153));

        btnConsultar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setPreferredSize(new java.awt.Dimension(147, 50));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultarLayout = new javax.swing.GroupLayout(pnlConsultar);
        pnlConsultar.setLayout(pnlConsultarLayout);
        pnlConsultarLayout.setHorizontalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlConsultarLayout.setVerticalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        grdUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "E-mail", "CPF", "Idade", "Sexo"
            }
        ));
        grdUsuarios.setMaximumSize(new java.awt.Dimension(2147483647, 4000));
        jScrollPane1.setViewportView(grdUsuarios);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nascimento:");

        edtNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        cbxSexo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cbxSexo.setMaximumRowCount(3);
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Masculino", "Feminino" }));

        edtEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Log:");

        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtLog.setRows(5);
        jScrollPane2.setViewportView(txtLog);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Senha:");

        ftxCPF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ftxCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxCPFActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefone:");

        ftxDataNasc.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ftxDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxDataNascActionPerformed(evt);
            }
        });

        pswSenha.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        pswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaActionPerformed(evt);
            }
        });

        ftxTelefone.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ftxTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxTelefoneActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Salário:");

        edtSalario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(14, 14, 14)
                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(edtNome)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFundoLayout.createSequentialGroup()
                                            .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(pnlFundoLayout.createSequentialGroup()
                                                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(62, 62, 62)
                                                    .addComponent(jLabel8))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                                                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel6)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ftxDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(pswSenha)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFundoLayout.createSequentialGroup()
                                            .addComponent(ftxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ftxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(edtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                                    .addComponent(pnlNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(pnlConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(pnlResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1)))
                .addGap(24, 24, 24))
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ftxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ftxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftxDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void criaDados() throws ParseException{
        SimpleDateFormat formatoDataTeste = new SimpleDateFormat("dd/MM/yyyy");
                Date dataTeste = formatoDataTeste.parse("01/01/2000");
        Leiturista u1 = new Leiturista("Fedor Emelianenko", "111.111.111-11", "(30) 91234-5678", "thelastemperor@hotmail.com", "123456", 
                "Masculino", dataTeste, 7000);
        this.lstUsuarios.add(u1);
        Leiturista u2 = new Leiturista("Charles Oliveira", "222.222.222-22", "(30) 91234-5678", "charlin2009@gmail.com", "000000", 
                "Masculino", dataTeste, 16550);
        this.lstUsuarios.add(u2);
        Leiturista u3 = new Leiturista("Valentina Shevchenko", "333.333.333-33", "(30) 91234-5678", "valetbullet@hotmail.com", "654321", 
                "Feminino", dataTeste, 13890);
        this.lstUsuarios.add(u3);
        Leiturista u4 = new Leiturista("Mirko Cro Cop", "444.444.444-44", "(30) 91234-5678", "crocop@gmail.com", "a2b4c8", 
                "Masculino", dataTeste, 27230);
        this.lstUsuarios.add(u4);
        Leiturista u5 = new Leiturista("Amanda Ribas", "555.555.555-55", "(30) 91234-5678", "mandinha@outlook.com", "abcdef",
                "Feminino", dataTeste, 6478);
        this.lstUsuarios.add(u5);
        
    }
    
    public void formatarCampos(){
        try {
            this.edtNome.setDocument(new PadraoLetras());
            this.edtSalario.setDocument(new PadraoNumeros());
            MaskFormatter maskData = new MaskFormatter("##/##/####");
            MaskFormatter maskCPF = new MaskFormatter("###.###.###-##");
            MaskFormatter maskTelefone = new MaskFormatter("(##) #####-####");
            maskCPF.install(ftxCPF);
            maskData.install(ftxDataNasc);
            maskTelefone.install(ftxTelefone);
        } catch (ParseException ex) {
            Logger.getLogger(FrCadastroLeiturista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean validarCPF(String cpf){
        int digito1 = 0, digito2 = 0, calculoDigito1 = 0, calculoDigito2 = 0, j = 10, z = 11;
        boolean repetido = true;
        digito1 = Integer.parseInt(cpf.substring(12, 13));
        digito2 = Integer.parseInt(cpf.substring(13, 14));
        cpf = cpf.substring(0, 3) + cpf.substring(4, 7) + cpf.substring(8, 11);
        int[] arrayCPF = new int[9];
        for(int i = 0; i < arrayCPF.length; i++) {
            arrayCPF[i] = Integer.parseInt(cpf.substring(i, i+1));
            calculoDigito1 += j * arrayCPF[i];
            j--;
            calculoDigito2 += z * arrayCPF[i];
            z--;
            if (arrayCPF[0] != arrayCPF[1] && repetido) {
                repetido = false;
            }        
        }
        calculoDigito2 += z * digito1;
        calculoDigito1 = (calculoDigito1 * 10) % 11;
        calculoDigito2 = (calculoDigito2 * 10) % 11;
        
        if (calculoDigito1 == 10) {
            calculoDigito1 = 0;
        }
        if (calculoDigito2 == 10) {
            calculoDigito2 = 0;
        }
        if(calculoDigito1 != digito1 || calculoDigito2 != digito2 || repetido == true){
            return false;
        }else{
            return true;
        }
    }
    
    public boolean validarCampos(){
        if(edtNome.getText().matches("{3,}") /*|| edtNome.getText().equals("")*/){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o nome corretamente.");
            edtNome.requestFocus();
            return false;
        }if(ftxCPF.getText().replace(" ","").length() < 14){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o CPF corretamente.");
            ftxCPF.requestFocus();
            return false;
        }else{
            if(!validarCPF(ftxCPF.getText())){
                JOptionPane.showMessageDialog(rootPane, "CPF Inválido!.");
                ftxCPF.setText("");
                ftxCPF.requestFocus();
                return false;
            }if(this.buscar(ftxCPF.getText()) != -1 && flagEdtSalvar == false){
                JOptionPane.showMessageDialog(rootPane, "CPF já cadastrado.");
                ftxCPF.setText("");
                ftxCPF.requestFocus();
                return false;
            }
        }if(ftxTelefone.getText().replace(" ","").length() < 13){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o telefone corretamente.");
            ftxTelefone.requestFocus();
            return false;
        }if(!edtEmail.getText().contains("@") || edtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o email corretamente.");
            edtEmail.requestFocus();
            return false;
        }if(pswSenha.getPassword().length < 6){
            JOptionPane.showMessageDialog(rootPane, "Por favor, a senha deve ter no mínimo 6 digitos.");
            pswSenha.requestFocus();
            return false;
        }if(cbxSexo.getSelectedItem().toString().equals("<Selecione>")){
            JOptionPane.showMessageDialog(rootPane, "Por favor selecione um sexo.");
            cbxSexo.requestFocus();
            return false;
        }if(ftxDataNasc.getText().replace(" ","").length() < 10){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite a data de nascimento corretamente.");
            ftxDataNasc.requestFocus();
            return false;
        }if(edtSalario.getText().replace(" ","").equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o salário corretamente.");
            edtSalario.requestFocus();
            return false;
        }
        return true;
    }
    
    public void habilitarBotoes(boolean novo, boolean cancelar, boolean editar, boolean excluir, boolean salvar, boolean consultar, boolean  voltar, boolean resetar){
        this.btnNovo.setEnabled(novo);
        this.btnCancelar.setEnabled(cancelar);
        this.btnEditar.setEnabled(editar);
        this.btnExcluir.setEnabled(excluir);
        this.btnSalvar.setEnabled(salvar);
        this.btnConsultar.setEnabled(consultar);
        this.btnVoltar.setEnabled(voltar);
        this.btnResetar.setEnabled(resetar);
    }
    
    public void resetFields(){
        edtNome.setText("");
        ftxCPF.setText("");
        ftxTelefone.setText("");
        edtEmail.setText("");
        pswSenha.setText("");
        ftxDataNasc.setText("");
        cbxSexo.setSelectedItem("<Selecione>");
        edtSalario.setText("");
    }
    
    public void habilitarCampos(boolean flag){
        for(int i=0; i<pnlFundo.getComponents().length; i++)
            pnlFundo.getComponent(i).setEnabled(flag);
    }
    
    public void atualizarTabela() {
        TMLeiturista tmusuario = new TMLeiturista(this.lstUsuarios);
        grdUsuarios.setModel(tmusuario);
    }
    
    public int buscar(String cpf){
        for(int i = 0; i < this.lstUsuarios.size(); i++){
            if(this.lstUsuarios.get(i).getCpf().equals(cpf)){
                return i;
            }
        }
        return -1;
    }
    
    public void atualizarLog(String s){
        this.txtLog.setText(this.txtLog.getText() + s + "\n");
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(validarCampos()){
            if(this.flagEdtSalvar == true && !(this.lstUsuarios.isEmpty())){
                this.lstUsuarios.remove(this.indice);
                this.atualizarLog("Usuário " + ftxCPF.getText() + " alterado.");
            }
            try {
                SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
                Date dataNasc = formatoData.parse(ftxDataNasc.getText());
                String senha = new String(pswSenha.getPassword());
                Leiturista usr = new Leiturista(edtNome.getText(), ftxCPF.getText(), ftxTelefone.getText(), edtEmail.getText(),
                                        senha, cbxSexo.getSelectedItem().toString(), dataNasc, Float.parseFloat(edtSalario.getText()));
                this.lstUsuarios.add(this.indice, usr);
                this.atualizarTabela();
                this.habilitarCampos(false);  
                this.habilitarBotoes(true, false, true, true, false, true, true, false);
                if(this.flagEdtSalvar == false){
                    this.atualizarLog("Usuário " + ftxCPF.getText() + " salvo.");
                }
                this.resetFields();
            } catch (ParseException ex) {
                Logger.getLogger(FrCadastroLeiturista.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.habilitarBotoes(false, true, false, false, true, false, false, false);
        this.resetFields();
        this.habilitarCampos(true);
        this.edtNome.requestFocus();
        this.indice = 0;
        this.flagCancelar = true;
        this.flagEdtSalvar = false;
        this.lstUsrTemp.clear();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrTelaPrincipal telaPrincipal = new FrTelaPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
        if(this.flagCancelar == true){
            this.resetFields();
            this.habilitarCampos(false);
        }else if(this.flagCancelar == false){
            this.btnSalvarActionPerformed(evt);
            this.resetFields();
            this.habilitarCampos(false);
        }
        this.atualizarTabela();
        this.atualizarLog("Operação cancelada.");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String cpfInformado = JOptionPane.showInputDialog("Informe o CPF do usuário a ser editado (com ponto e hífen): ");
        int index = this.buscar(cpfInformado);
        this.indice = index;
        if(this.indice == -1){
            JOptionPane.showMessageDialog(rootPane, "Usuário não encontrado.");
        }else if(!cpfInformado.equals(null)){
            this.habilitarBotoes(false, true, false, false, true, false, false, false);
            this.habilitarCampos(true);
            this.edtNome.setText(this.lstUsuarios.get(index).getNome());
            this.ftxCPF.setText(this.lstUsuarios.get(index).getCpf()+"");
            this.ftxTelefone.setText(this.lstUsuarios.get(index).getTelefone());
            this.edtEmail.setText(this.lstUsuarios.get(index).getEmail());
            this.pswSenha.setText(this.lstUsuarios.get(index).getSenha());
            this.cbxSexo.setSelectedItem(this.lstUsuarios.get(index).getSexo());
            SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
            Date dataNasc = this.lstUsuarios.get(index).getDataNasc();
            String dataString = formatoData.format(dataNasc);
            this.ftxDataNasc.setText(dataString);
            this.edtSalario.setText(this.lstUsuarios.get(index).getSalario()+"");
            this.flagCancelar = true;
            this.flagEdtSalvar = true;
            this.lstUsrTemp.clear();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String cpfInformado = JOptionPane.showInputDialog("Informe o CPF do usuário a ser excluído (com ponto e hífen): ");
        this.indice = this.buscar(cpfInformado);
        if(this.indice == -1){
            JOptionPane.showMessageDialog(rootPane, "Usuário não encontrado.");
        }else if(!cpfInformado.equals(null)){
            this.habilitarBotoes(true, false, true, true, false, true, true, false);
            this.lstUsuarios.remove(indice);  
            this.atualizarTabela();
            this.resetFields();
            this.habilitarCampos(false);
            this.atualizarLog("Usuário " + cpfInformado + " excluído.");
            this.lstUsrTemp.clear();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String cpfInformado = JOptionPane.showInputDialog("Informe um CPF (com ponto e hífen): ");
        int index = this.buscar(cpfInformado);
        this.indice = index;
        if(cpfInformado.equals(null)){
            this.atualizarLog("Operação cancelada.");
        }else if(this.indice == -1){
            JOptionPane.showMessageDialog(rootPane, "Usuário não encontrado.");
        }else{
            this.habilitarBotoes(true, false, true, true, false, true, true, true);
            this.habilitarCampos(false);
            this.flagCancelar = true;
            this.flagEdtSalvar = true;
            this.atualizarLog("Busca concluída");
            this.lstUsrTemp.add(this.lstUsuarios.get(index));
            TMLeiturista tmusrTemp = new TMLeiturista(this.lstUsrTemp);
            grdUsuarios.setModel(tmusrTemp);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
        this.lstUsrTemp.clear();
        this.atualizarTabela();
    }//GEN-LAST:event_btnResetarActionPerformed

    private void ftxCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxCPFActionPerformed

    private void ftxDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxDataNascActionPerformed

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswSenhaActionPerformed

    private void ftxTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadastroLeiturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadastroLeiturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadastroLeiturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadastroLeiturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrCadastroLeiturista().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrCadastroLeiturista.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtSalario;
    private javax.swing.JFormattedTextField ftxCPF;
    private javax.swing.JFormattedTextField ftxDataNasc;
    private javax.swing.JFormattedTextField ftxTelefone;
    private javax.swing.JTable grdUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlCancelar;
    private javax.swing.JPanel pnlConsultar;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlExcluir;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JPanel pnlNovo;
    private javax.swing.JPanel pnlResetar;
    private javax.swing.JPanel pnlSalvar;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
