package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.*;
import controller.*;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;

public class FrCadastroUnidCons extends javax.swing.JFrame {
    
    //Para testes ativar a chamada da função criaDados()
    
    private ArrayList<UnidadeConsumidora> lstUsuarios;
    private ArrayList<UnidadeConsumidora> lstUsrTemp;
    private boolean flagCancelar;
    private boolean flagEdtSalvar;
    private int indice;
    
    public FrCadastroUnidCons() throws ParseException {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);//Maximizar
        this.formatarCampos();
        this.setVisible(true);
        indice = 0;
        this.lstUsuarios = new ArrayList();
        this.lstUsrTemp = new ArrayList();
        this.flagCancelar = false;
        this.flagEdtSalvar = false;
        this.criaDados(); //Dados para testes
        atualizarTabela();
        this.habilitarCampos(false);
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pnlNovo = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        pnlCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        pnlEditar = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        pnlExcluir = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        pnlSalvar = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        pnlResetar = new javax.swing.JPanel();
        btnResetar = new javax.swing.JButton();
        pnlConsultar = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdUsuarios = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        ftxCPF = new javax.swing.JFormattedTextField();
        edtConsumo = new javax.swing.JTextField();
        edtEndereco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFundo.setBackground(new java.awt.Color(0, 0, 48));
        pnlFundo.setForeground(new java.awt.Color(0, 0, 51));

        pnlTitulo.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Unidade Consumidora");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVoltar.setBackground(new java.awt.Color(0, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVoltar.setPreferredSize(new java.awt.Dimension(61, 50));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(271, 271, 271)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNovo.setBackground(new java.awt.Color(0, 153, 153));
        pnlNovo.setPreferredSize(new java.awt.Dimension(95, 50));

        btnNovo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.setContentAreaFilled(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNovoLayout = new javax.swing.GroupLayout(pnlNovo);
        pnlNovo.setLayout(pnlNovoLayout);
        pnlNovoLayout.setHorizontalGroup(
            pnlNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNovoLayout.setVerticalGroup(
            pnlNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlCancelar.setBackground(new java.awt.Color(0, 153, 153));
        pnlCancelar.setPreferredSize(new java.awt.Dimension(135, 50));

        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(135, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCancelarLayout = new javax.swing.GroupLayout(pnlCancelar);
        pnlCancelar.setLayout(pnlCancelarLayout);
        pnlCancelarLayout.setHorizontalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCancelarLayout.setVerticalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlEditar.setBackground(new java.awt.Color(0, 153, 153));
        pnlEditar.setPreferredSize(new java.awt.Dimension(101, 50));

        btnEditar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPreferredSize(new java.awt.Dimension(101, 50));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlExcluir.setBackground(new java.awt.Color(0, 153, 153));
        pnlExcluir.setPreferredSize(new java.awt.Dimension(111, 50));

        btnExcluir.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setPreferredSize(new java.awt.Dimension(111, 50));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExcluirLayout = new javax.swing.GroupLayout(pnlExcluir);
        pnlExcluir.setLayout(pnlExcluirLayout);
        pnlExcluirLayout.setHorizontalGroup(
            pnlExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlExcluirLayout.setVerticalGroup(
            pnlExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSalvar.setBackground(new java.awt.Color(0, 153, 153));
        pnlSalvar.setPreferredSize(new java.awt.Dimension(107, 50));

        btnSalvar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setPreferredSize(new java.awt.Dimension(107, 50));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalvarLayout = new javax.swing.GroupLayout(pnlSalvar);
        pnlSalvar.setLayout(pnlSalvarLayout);
        pnlSalvarLayout.setHorizontalGroup(
            pnlSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSalvarLayout.setVerticalGroup(
            pnlSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlResetar.setBackground(new java.awt.Color(0, 153, 153));

        btnResetar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnResetar.setForeground(new java.awt.Color(255, 255, 255));
        btnResetar.setText("Resetar");
        btnResetar.setBorderPainted(false);
        btnResetar.setContentAreaFilled(false);
        btnResetar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnResetar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetar.setPreferredSize(new java.awt.Dimension(123, 50));
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResetarLayout = new javax.swing.GroupLayout(pnlResetar);
        pnlResetar.setLayout(pnlResetarLayout);
        pnlResetarLayout.setHorizontalGroup(
            pnlResetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlResetarLayout.setVerticalGroup(
            pnlResetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlConsultar.setBackground(new java.awt.Color(0, 153, 153));

        btnConsultar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setPreferredSize(new java.awt.Dimension(147, 50));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultarLayout = new javax.swing.GroupLayout(pnlConsultar);
        pnlConsultar.setLayout(pnlConsultarLayout);
        pnlConsultarLayout.setHorizontalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlConsultarLayout.setVerticalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        grdUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Bairro", "Consumo", "Alcance"
            }
        ));
        grdUsuarios.setMaximumSize(new java.awt.Dimension(2147483647, 4000));
        jScrollPane1.setViewportView(grdUsuarios);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Proprietário (CPF):");

        edtId.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Log:");

        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtLog.setRows(5);
        jScrollPane2.setViewportView(txtLog);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Consumo:");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Endereço:");

        cbxTipo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Comercial", "Público", "Residencial" }));

        ftxCPF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        edtConsumo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        edtEndereco.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                                    .addComponent(pnlNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlFundoLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlFundoLayout.createSequentialGroup()
                                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8)
                                                    .addGroup(pnlFundoLayout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(82, 82, 82)
                                                        .addComponent(jLabel4)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(226, 226, 226)))
                                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ftxCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(edtConsumo))))
                                .addGap(15, 15, 15))))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(pnlConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(pnlResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1)))
                .addGap(24, 24, 24))
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(ftxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void criaDados() throws ParseException{
        SimpleDateFormat formatoDataTeste = new SimpleDateFormat("dd/MM/yyyy");
        Date dataTeste = formatoDataTeste.parse("01/01/2000");
        Cliente cTeste = new Cliente();
        cTeste.setCpf("111.111.000-00");
        UnidadeConsumidora u1 = new UnidadeConsumidora(1 ,"Residencial", "Rua Z, 150 - Centro", cTeste, (float)3000.0);
        this.lstUsuarios.add(u1);
        UnidadeConsumidora u2 = new UnidadeConsumidora(2, "Comercial", "Rua Z, 379 - Centro", cTeste, (float)42000.0);
        this.lstUsuarios.add(u2);
        UnidadeConsumidora u3 = new UnidadeConsumidora(3, "Residencial", "Av H, 4704 - Santa Aliança", cTeste, (float)1500.0);
        this.lstUsuarios.add(u3);
        UnidadeConsumidora u4 = new UnidadeConsumidora(4, "Público", "Rua I, 89 - Santa Aliança", cTeste, (float)230000.0);
        this.lstUsuarios.add(u4);
        UnidadeConsumidora u5 = new UnidadeConsumidora(5, "Comercial", "Rua C, 26 - Barbante", cTeste, (float)63200.0);
        this.lstUsuarios.add(u5);
        
    }
    
    public void formatarCampos(){
        try {
            this.edtId.setDocument(new PadraoNumeros());
            MaskFormatter maskCPF = new MaskFormatter("###.###.###-##");
            maskCPF.install(ftxCPF);
            this.edtConsumo.setDocument(new PadraoNumeros());
            this.txtLog.setEditable(false);
            this.atualizarLog("Programa iniciado.");
        } catch (ParseException ex) {
            Logger.getLogger(FrCadastroServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean validarCPF(String cpf){
        int digito1 = 0, digito2 = 0, calculoDigito1 = 0, calculoDigito2 = 0, j = 10, z = 11;
        boolean repetido = true;
        digito1 = Integer.parseInt(cpf.substring(12, 13));
        digito2 = Integer.parseInt(cpf.substring(13, 14));
        cpf = cpf.substring(0, 3) + cpf.substring(4, 7) + cpf.substring(8, 11);
        int[] arrayCPF = new int[9];
        for(int i = 0; i < arrayCPF.length; i++) {
            arrayCPF[i] = Integer.parseInt(cpf.substring(i, i+1));
            calculoDigito1 += j * arrayCPF[i];
            j--;
            calculoDigito2 += z * arrayCPF[i];
            z--;
            if (arrayCPF[0] != arrayCPF[1] && repetido) {
                repetido = false;
            }        
        }
        calculoDigito2 += z * digito1;
        calculoDigito1 = (calculoDigito1 * 10) % 11;
        calculoDigito2 = (calculoDigito2 * 10) % 11;
        
        if (calculoDigito1 == 10) {
            calculoDigito1 = 0;
        }
        if (calculoDigito2 == 10) {
            calculoDigito2 = 0;
        }
        if(calculoDigito1 != digito1 || calculoDigito2 != digito2 || repetido == true){
            return false;
        }else{
            return true;
        }
    }
    
    public boolean validarCampos(){
        if(edtId.getText().replace(" ","").equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o ID corretamente.");
            edtId.requestFocus();
            return false;
        }else{
            if(this.buscar(Integer.parseInt(edtId.getText())) != -1 && flagEdtSalvar == false){
                JOptionPane.showMessageDialog(rootPane, "ID já cadastrado.");
                edtId.setText("");
                edtId.requestFocus();
                return false;
            }
        }if(cbxTipo.getSelectedItem().toString().equals("<Selecione>")){
            JOptionPane.showMessageDialog(rootPane, "Por favor selecione um tipo.");
            cbxTipo.requestFocus();
            return false;
        }if(ftxCPF.getText().replace(" ","").length() < 14){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o CPF corretamente.");
            ftxCPF.requestFocus();
            return false;
        }else{
            if(!validarCPF(ftxCPF.getText())){
                JOptionPane.showMessageDialog(rootPane, "CPF Inválido!");
                ftxCPF.setText("");
                ftxCPF.requestFocus();
                return false;
            }
        }if(edtEndereco.getText().replace(" ","").equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o endereço corretamente.");
            edtEndereco.requestFocus();
            return false;
        }if(edtConsumo.getText().replace(" ","").equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o consumo corretamente.");
            edtConsumo.requestFocus();
            return false;
        }
        return true;
    }
    
    public void habilitarBotoes(boolean novo, boolean cancelar, boolean editar, boolean excluir, boolean salvar, boolean consultar, boolean  voltar, boolean resetar){
        this.btnNovo.setEnabled(novo);
        this.btnCancelar.setEnabled(cancelar);
        this.btnEditar.setEnabled(editar);
        this.btnExcluir.setEnabled(excluir);
        this.btnSalvar.setEnabled(salvar);
        this.btnConsultar.setEnabled(consultar);
        this.btnVoltar.setEnabled(voltar);
        this.btnResetar.setEnabled(resetar);
    }
    
    public void resetFields(){
        edtId.setText("");
        cbxTipo.setSelectedItem("<Selecione>");
        edtEndereco.setText("");
        ftxCPF.setText("");
        edtConsumo.setText("");
    }
    
    public void habilitarCampos(boolean flag){
        for(int i=0; i<pnlFundo.getComponents().length; i++)
            pnlFundo.getComponent(i).setEnabled(flag);
    }
    
    public void atualizarTabela() {
        TMUnidCons tmusuario = new TMUnidCons(this.lstUsuarios);
        grdUsuarios.setModel(tmusuario);
    }
    
    public int buscar(int id){
        for(int i = 0; i < this.lstUsuarios.size(); i++){
            if(this.lstUsuarios.get(i).getId() == id){
                return i;
            }
        }
        return -1;
    }
    
    public void atualizarLog(String s){
        this.txtLog.setText(this.txtLog.getText() + s + "\n");
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(validarCampos()){
            if(this.flagEdtSalvar == true && !(this.lstUsuarios.isEmpty())){
                this.lstUsuarios.remove(this.indice);
                this.atualizarLog("Unidade Consumidora " + edtId.getText() + " alterada.");
            }
            Cliente cTeste = new Cliente();
            cTeste.setCpf(this.ftxCPF.getText());
            UnidadeConsumidora usr = new UnidadeConsumidora(Integer.parseInt(edtId.getText()), cbxTipo.getSelectedItem().toString(),
                    edtEndereco.getText(), cTeste, Float.parseFloat(edtConsumo.getText()));
            this.lstUsuarios.add(this.indice, usr);
            this.atualizarTabela();
            this.habilitarCampos(false);
            this.habilitarBotoes(true, false, true, true, false, true, true, false);
            if(this.flagEdtSalvar == false){
                this.atualizarLog("Unidade Consumidora " + edtId.getText() + " salva.");
            }
            this.resetFields();
        }        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.habilitarBotoes(false, true, false, false, true, false, false, false);
        this.resetFields();
        this.habilitarCampos(true);
        this.edtId.requestFocus();
        this.indice = 0;
        this.flagCancelar = true;
        this.flagEdtSalvar = false;
        this.lstUsrTemp.clear();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrTelaPrincipal telaPrincipal = new FrTelaPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
        if(this.flagCancelar == true){
            this.resetFields();
            this.habilitarCampos(false);
        }else if(this.flagCancelar == false){
            this.btnSalvarActionPerformed(evt);
            this.resetFields();
            this.habilitarCampos(false);
        }
        this.atualizarTabela();
        this.atualizarLog("Operação cancelada.");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int idInformado = Integer.parseInt(JOptionPane.showInputDialog("Informe o ID da Unidade Consumidora a ser editada: "));
        int index = this.buscar(idInformado);
        this.indice = index;
        if(this.indice == -1){
            JOptionPane.showMessageDialog(rootPane, "Unidade Consumidora não encontrada.");
        }else if(idInformado > 0){
            this.habilitarBotoes(false, true, false, false, true, false, false, false);
            this.habilitarCampos(true);
            Cliente cTeste = new Cliente();
            cTeste.setCpf(this.ftxCPF.getText());
            this.edtId.setText(this.lstUsuarios.get(index).getId()+"");
            this.cbxTipo.setSelectedItem(this.lstUsuarios.get(index).getTipo());
            this.ftxCPF.setText(this.lstUsuarios.get(index).getProprietario().getCpf());
            this.edtEndereco.setText(this.lstUsuarios.get(index).getEndereco());
            this.edtConsumo.setText(this.lstUsuarios.get(index).getConsumo()+"");
            this.flagCancelar = true;
            this.flagEdtSalvar = true;
            this.lstUsrTemp.clear();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int idInformado = Integer.parseInt(JOptionPane.showInputDialog("Informe o ID da Unidade Consumidora a ser excluída: "));
        this.indice = this.buscar(idInformado);
        if(this.indice == -1){
            JOptionPane.showMessageDialog(rootPane, "Unidade Consumidora não encontrada.");
        }else if(idInformado > 0){
            this.habilitarBotoes(true, false, true, true, false, true, true, false);
            this.lstUsuarios.remove(indice);  
            this.atualizarTabela();
            this.resetFields();
            this.habilitarCampos(false);
            this.atualizarLog("Unidade Consumidora " + idInformado + " excluída.");
            this.lstUsrTemp.clear();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int idInformado = Integer.parseInt(JOptionPane.showInputDialog("Informe um ID: "));
        int index = this.buscar(idInformado);
        this.indice = index;
        if(idInformado < 0){
            this.atualizarLog("Operação cancelada.");
        }else if(this.indice == -1){
            JOptionPane.showMessageDialog(rootPane, "Unidade Consumidora não encontrada.");
        }else{
            this.habilitarBotoes(true, false, true, true, false, true, true, true);
            this.habilitarCampos(false);
            this.flagCancelar = true;
            this.flagEdtSalvar = true;
            this.atualizarLog("Busca concluída");
            this.lstUsrTemp.add(this.lstUsuarios.get(index));
            TMUnidCons tmusrTemp = new TMUnidCons(this.lstUsrTemp);
            grdUsuarios.setModel(tmusrTemp);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
        this.lstUsrTemp.clear();
        this.atualizarTabela();
    }//GEN-LAST:event_btnResetarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadastroUnidCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadastroUnidCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadastroUnidCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadastroUnidCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrCadastroUnidCons().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrCadastroUnidCons.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JTextField edtConsumo;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtId;
    private javax.swing.JFormattedTextField ftxCPF;
    private javax.swing.JTable grdUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlCancelar;
    private javax.swing.JPanel pnlConsultar;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlExcluir;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JPanel pnlNovo;
    private javax.swing.JPanel pnlResetar;
    private javax.swing.JPanel pnlSalvar;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
